export const initialState = {
  posts: {
    data: [
      {
        id: 1,
        title: 'Lorem ipsum dolor',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        price: 19,
        image: 'https://images.pexels.com/photos/1925099/pexels-photo-1925099.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
        publicationDate: '09/09/2021',
        updateDate: '10/09/2021',
        email: 'john.doe@example.com',
        phone: '123-456-789',
        location: 'Akra',
        status: 'published',
      },
      {
        id: 2,
        title: 'Ipsum dolor volupt',
        content: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
        price: 29,
        image: 'https://images.pexels.com/photos/1389429/pexels-photo-1389429.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
        publicationDate: '09/08/2021',
        updateDate: '24/08/2021',
        email: 'tina.turner@example.com',
        phone: '234-567-890',
        location: 'Boston',
        status: 'published',
      },
      {
        id: 3,
        title: 'Lorem ipsum dolor',
        content: 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        price: 39,
        image: 'https://images.pexels.com/photos/1261578/pexels-photo-1261578.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
        publicationDate: '14/08/2021',
        updateDate: '01/09/2021',
        email: 'barak.obama@example.com',
        phone: '345-678-901',
        location: 'Lisbona',
        status: 'closed',
      },
      {
        id: 4,
        title: 'Lorem ipsum dolor',
        content: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
        price: 49,
        image: 'https://images.pexels.com/photos/1616470/pexels-photo-1616470.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
        publicationDate: '02/09/2021',
        updateDate: '07/09/2021',
        email: 'eric.clapton@example.com',
        phone: '456-789-012',
        location: 'Bombay',
        status: 'published',
      },
    ],
    loading: {
      active: false,
      error: false,
    },
  },
  user: {
    userStatus: 'is loggedOut',
    userEmail: {},
  },
};
